# OpenAPI Contract: Todo Application Database Endpoints

openapi: 3.0.0
info:
  title: Todo Application API
  version: 1.0.0
  description: API for managing todo items in a multi-user application

paths:
  /api/{user_id}/tasks:
    get:
      summary: Get all tasks for a specific user
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID to retrieve tasks for
          schema:
            type: string
      responses:
        '200':
          description: List of tasks for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - trying to access another user's tasks
    post:
      summary: Create a new task for a user
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID to create task for
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /api/{user_id}/tasks/{task_id}:
    get:
      summary: Get a specific task for a user
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - trying to access another user's task
        '404':
          description: Task not found
    put:
      summary: Update a specific task for a user
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - trying to access another user's task
        '404':
          description: Task not found
    delete:
      summary: Delete a specific task for a user
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - trying to access another user's task
        '404':
          description: Task not found

  /api/{user_id}/tasks/{task_id}/status:
    patch:
      summary: Update the completion status of a task
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
                  description: New completion status for the task
      responses:
        '200':
          description: Task status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - trying to access another user's task
        '404':
          description: Task not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the user (UUID format)
        email:
          type: string
          description: User's email address
      required:
        - id
        - email

    TaskBase:
      type: object
      properties:
        title:
          type: string
          maxLength: 100
          description: Title of the task
        description:
          type: string
          nullable: true
          description: Optional description of the task
        completed:
          type: boolean
          default: false
          description: Completion status of the task
      required:
        - title

    Task:
      allOf:
        - $ref: '#/components/schemas/TaskBase'
        - type: object
          properties:
            id:
              type: string
              description: Unique identifier for the task (UUID format)
            created_at:
              type: string
              format: date-time
              description: When the task was created
            updated_at:
              type: string
              format: date-time
              description: When the task was last updated
            user_id:
              type: string
              description: ID of the user who owns this task
          required:
            - id
            - created_at
            - updated_at
            - user_id

    TaskCreate:
      allOf:
        - $ref: '#/components/schemas/TaskBase'

    TaskUpdate:
      allOf:
        - $ref: '#/components/schemas/TaskBase'